# Generated by Django 3.2.20 on 2023-09-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_recipe_star_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_category',
            field=models.CharField(choices=[('Starters', 'Starters'), ('Bread', 'Bread'), ('Vegetarian', 'Vegetarian'), ('Pasta', 'Pasta'), ('Oven Meals', 'Oven Meals'), ('Eastern Food', 'Eastern Food'), ('Quick Meals', 'Quick Meals'), ('Beverage', 'Beverage'), ('Desserts', 'Desserts'), ('Cakes', 'Cakes'), ('Other', 'Other')], default='Quick Meals', max_length=20),
        ),
    ]
