# Generated by Django 3.2.20 on 2023-09-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_recipe_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_category',
            field=models.CharField(choices=[('Starters', 'Starters'), ('Bread', 'Bread'), ('Vegetarian', 'Vegetarian'), ('Pasta', 'Pasta'), ('Oven Meals', 'Oven Meals'), ('Eastern Food', 'Eastern Food'), ('Quick Meals', 'Quick Meals'), ('Beverages', 'Beverages'), ('Desserts', 'Desserts'), ('Cakes', 'Cakes'), ('Other', 'Other')], default='Quick Meals', max_length=20),
        ),
    ]
