# Generated by Django 3.2.20 on 2023-09-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_recipe_recipe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='portions',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
