# Generated by Django 3.2.20 on 2023-09-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_recipe_portions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='portions',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
